name = "everest-bot-2"
main = "src/index.js"
compatibility_date = "2026-09-24"

[triggers]
crons = ["*/5 * * * *"]

[vars]
GEMINI_MODEL = "gemini-3.5-flash-lite"

[[kv_namespaces]]
binding = "KV"
id = "62b3054c06c14f80979d407ec44d357b"
